### ISSUE TITLE
ERROR while Installing

### ISSUE THREAD

**Issue by ghost** [jtebert/jekyll-polymer#11]
@jtebert I am getting an error: `ECONFLICT Unable to find suitable version for polymer`

I am running `npm install && bower install` in Netlify CMS. Any idea why I am getting this?

**Comment by jtebert** [comment]
This seems to be an issue with the specification for the Polymer version in `bower.json`. I don't have the time right now to debug the issue myself with a fresh test installation. However, Googling the error gives a number of straightforward suggestions for respecifying the version in `bower.json` to solve the installation problem, like [this one](https://github.com/zacharytamas/page-title/issues/1) -- replacing `#^` with `^`. I'm admittedly not very familiar with the versioning system in Bower, though.

Please let me know if you find a solution in case it's a necessary general update.

**Comment by ghost** [comment]
I found a solution, but I can't remember where it was! Either way, this has been resolved.

**Comment by samcarecho** [comment]
@PartialDevAdmin you can read the actual code on Master, but you should not use it, as Polymer 1 is now deprecated. 
Also, installing the version available on Master is just a waste of time as we will soon have a Polymer 2 version.

**Comment by ghost** [comment]
Ok
