### ISSUE TITLE
Scrolling through the posts

### ISSUE THREAD

**Issue by Quasimobi** [jtebert/jekyll-polymer#8]
At the home-page the posts are listed from recent posts to older. When a person scrolls through the posts its goes from top to bottom,  from recent to "old". So a previous post would be a more recent post.
When you go from a short post to a full post. There are two buttons at the bottom of the page. With the previous button a older post is shown. Is it not more logical to go with previous button to a newer post and with the next button to an older? 

Many thanks for the nice work of combining Polymer and Jekyll, 

Bauke

**Comment by jtebert** [comment]
Thanks for your input.

My reasoning was that it would be incongruous to have "previous" refer to the future and "next" refer to the past. One approach, as shown in [this theme](https://ferrolho.github.io/jekyll-theme-libretto/2016/08/20/bacon-ipsum.html) could be to swap the position of the buttons to make the navigation more intuitive with the layout on the homepage.

If you're interested in using the theme yourself, it's also very easy to edit the button text to your liking. The code in question is in `app/_layouts/post.html` on lines 51-71 (as of the current commit).

I'll give this some thought and look around at what the convention seems to be for this type of navigation.
